spring:
  application:
    name: nbc-checkout-system
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

portone:
  base-url: "https://api.portone.io"
  api-secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}