spring:
  application:
    name: nbc-checkout-system

jwt:
  secret: ${JWT_SECRET:bmJjLWNoZWNrb3V0LXN5c3RlbS1qd3Qtc2VjcmV0LWtleS1mb3ItYm9vdGNhbXAtMjAyNi12ZXJ5LWxvbmctc2VjcmV0LWtleQ==}
  expiration: ${JWT_EXPIRATION:3600000}
