name: 프로젝트 진행 제안서
description: 프로젝트 진행하는데에 있어 제안이 있을 경우 제안하기 위한 이슈
labels: ["SUGGESTION"]
assignees: []
projects: ["Astro-Luminoso/2"]

body:
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: '프로젝트 진행 방향에 있어 이렇게 하면 어떨까?' 하는 제안이 있다면 자유롭게 작성해 주세요.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: 제안한 방향이 왜 좋은지에 대한 근거를 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: effect
    attributes:
      label: Expected Effect
      description: 제안한 방향이 실제로 적용되었을 때 어떤 효과가 있을지 작성해주세요.
    validations:
      required: true
